# Generated by Django 5.2.1 on 2025-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_facebook_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("class", "Group Class"),
                            ("private_lesson", "Private Lesson"),
                            ("workshop", "Workshop"),
                            ("package", "Class Package"),
                            ("event", "Special Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("class_name", models.CharField(max_length=100)),
                ("instructor_name", models.CharField(blank=True, max_length=100)),
                ("booking_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                (
                    "location",
                    models.CharField(
                        default="Avalon Ballroom, Boulder, CO", max_length=200
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("pending", "Pending Payment"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("calendly_event_id", models.CharField(blank=True, max_length=100)),
                ("google_calendar_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmation_email_sent", models.BooleanField(default=False)),
                ("reminder_email_sent", models.BooleanField(default=False)),
                ("follow_up_email_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Booking Confirmation",
                "verbose_name_plural": "Booking Confirmations",
                "ordering": ["-booking_date"],
                "indexes": [
                    models.Index(
                        fields=["booking_date", "status"],
                        name="core_bookin_booking_1bdb54_idx",
                    ),
                    models.Index(
                        fields=["customer_email", "status"],
                        name="core_bookin_custome_aac360_idx",
                    ),
                    models.Index(
                        fields=["booking_type", "booking_date"],
                        name="core_bookin_booking_becd59_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("classes", "Group Classes"),
                            ("private_lesson", "Private Lessons"),
                            ("workshop", "Workshops"),
                            ("events", "Events & Performances"),
                            ("choreography", "Choreography Services"),
                            ("general", "General Inquiry"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="website",
                        help_text="Where the contact came from",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes for staff"),
                ),
                ("admin_notification_sent", models.BooleanField(default=False)),
                ("auto_reply_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="core_contac_status_19aa2c_idx",
                    ),
                    models.Index(
                        fields=["created_at", "status"],
                        name="core_contac_created_ceae85_idx",
                    ),
                    models.Index(
                        fields=["interest", "status"],
                        name="core_contac_interes_ea6795_idx",
                    ),
                ],
            },
        ),
    ]
