# Generated by Django 5.2.1 on 2025-08-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("choreo_team", "SCF Choreo Team"),
                    ("pasos_basicos", "Pasos Básicos"),
                    ("casino_royale", "Casino Royale"),
                    ("private_lesson", "Private Lesson"),
                    ("workshop", "Workshop"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
