# Generated by Django 5.2.1 on 2025-08-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_testimonial_class_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=32, unique=True)),
                ("instructor_name", models.CharField(blank=True, max_length=100)),
                ("class_type", models.CharField(blank=True, max_length=50)),
                ("campaign_name", models.CharField(blank=True, max_length=100)),
                ("created_by", models.CharField(default="System", max_length=100)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Review Link",
                "verbose_name_plural": "Review Links",
                "ordering": ["-created_at"],
            },
        ),
    ]
