# Generated by Django 5.2.1 on 2025-08-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_reviewlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewlink",
            name="campaign_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
