# Generated by Django 5.2.1 on 2025-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_reviewlink_campaign_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("class", "Class"),
                            ("performance", "Performance"),
                            ("social", "Social Dance"),
                            ("workshop", "Workshop"),
                            ("event", "Event"),
                            ("team", "Team Photos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="gallery/%Y/%m/"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="External URL for video or image"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/thumbs/%Y/%m/"
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                ("event", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Comma-separated tags"),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Media Gallery",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
