# Generated by Django 5.2.1 on 2025-08-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_instagram_integration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("formatted_date", models.CharField(blank=True, max_length=50)),
                ("formatted_time", models.CharField(blank=True, max_length=20)),
                ("cover_photo_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField()),
                ("location_name", models.CharField(blank=True, max_length=200)),
                ("location_address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facebook Event",
                "verbose_name_plural": "Facebook Events",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["start_time", "is_active"],
                        name="core_facebo_start_t_887051_idx",
                    ),
                    models.Index(
                        fields=["featured", "start_time"],
                        name="core_facebo_feature_ede859_idx",
                    ),
                ],
            },
        ),
    ]
