# Generated by Django 5.2.1 on 2025-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_spotify_playlists"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSVPSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "class_id",
                    models.CharField(
                        help_text="Internal class identifier", max_length=50
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pastio", "Pastio.fun"),
                            ("website", "Website Direct"),
                            ("facebook", "Facebook Event"),
                            ("instagram", "Instagram"),
                            ("other", "Other"),
                        ],
                        default="pastio",
                        max_length=20,
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Send reminders and updates"
                    ),
                ),
                (
                    "pastio_id",
                    models.CharField(
                        blank=True,
                        help_text="Pastio.fun RSVP ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "facebook_event_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Dietary restrictions, accessibility needs, etc.",
                    ),
                ),
                (
                    "plus_one",
                    models.BooleanField(default=False, help_text="Bringing a plus one"),
                ),
                ("plus_one_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attended",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether they actually attended",
                        null=True,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "RSVP Submission",
                "verbose_name_plural": "RSVP Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["class_id", "status"],
                        name="core_rsvpsu_class_i_76ee6c_idx",
                    ),
                    models.Index(
                        fields=["created_at", "status"],
                        name="core_rsvpsu_created_e3b55b_idx",
                    ),
                    models.Index(
                        fields=["email", "class_id"],
                        name="core_rsvpsu_email_cce234_idx",
                    ),
                    models.Index(
                        fields=["pastio_id"], name="core_rsvpsu_pastio__6762a1_idx"
                    ),
                ],
                "unique_together": {("email", "class_id", "created_at")},
            },
        ),
    ]
