"""
Django settings for sabor_con_flow project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file for local development if it exists
# Vercel will use its own environment variables, not this file
dotenv_path = BASE_DIR / '.env'
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY and not os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't'):
    raise ValueError("SECRET_KEY environment variable not set in production.")
elif not SECRET_KEY:
    print("Warning: SECRET_KEY environment variable not set. Using a default for local DEBUG mode.")
    SECRET_KEY = 'django-insecure-local-debug-key-replace-me-for-real-local-dev'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't')

# Configure ALLOWED_HOSTS from an environment variable
ALLOWED_HOSTS_STRING = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app,www.saborconflowdance.com,saborconflowdance.com,www.saborconflowdance.org,saborconflowdance.org,www.saborconflowdance.info,saborconflowdance.info')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(',')] if ALLOWED_HOSTS_STRING else []
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.PerformanceMiddleware',
    'core.middleware.monitoring.MonitoringMiddleware',  # SPEC_06 Group C Task 9
    'core.middleware.monitoring.HealthCheckCacheMiddleware',  # SPEC_06 Group C Task 9
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.CacheControlMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.ETagMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Database performance monitoring middleware
    'core.middleware.DatabasePerformanceMiddleware',
    'core.middleware.QueryCountDebugMiddleware',
]

ROOT_URLCONF = 'sabor_con_flow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.analytics_settings',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'sabor_con_flow.wsgi.application'

# Database Configuration
# For now using standard SQLite3, ready to switch to Turso when credentials available
TURSO_DATABASE_URL = os.environ.get('TURSO_DATABASE_URL')
TURSO_AUTH_TOKEN = os.environ.get('TURSO_AUTH_TOKEN')

# Database configuration - supports both local SQLite and Turso
if TURSO_DATABASE_URL and TURSO_AUTH_TOKEN:
    # Turso configuration (when credentials are available)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': TURSO_DATABASE_URL,
            'OPTIONS': {
                'init_command': f"PRAGMA foreign_keys=ON; PRAGMA auth_token='{TURSO_AUTH_TOKEN}';",
            },
        }
    }
else:
    # Local SQLite configuration (fallback for development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'init_command': 'PRAGMA foreign_keys=ON;',
            },
        }
    }

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Static file configuration for Vercel with compression and cache busting
if not DEBUG:
    # Use WhiteNoise for static file serving in production with compression
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Enable compression for WhiteNoise
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
    
    # Cache busting and compression settings
    WHITENOISE_MAX_AGE = 31536000  # 1 year cache for static assets
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br']
    WHITENOISE_MANIFEST_STRICT = False  # Allow missing files in manifest
    
    # Static file versioning for cache busting
    STATICFILES_HASH_VERSIONING = True
else:
    # Development static files configuration
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Static file finders for performance
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Settings for Vercel
CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'https://www.saborconflowdance.com',
    'https://www.saborconflowdance.org',
    'https://www.saborconflowdance.info'
]

# Removed Crispy Forms Settings (no longer needed without forms)

# Media files - removed (not needed for static site)

# Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Disable SSL redirect for Vercel
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'database_performance': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Caching Configuration for Performance
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'sabor-con-flow-cache',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
    },
    'page_cache': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'page-cache',
        'TIMEOUT': 3600,  # 1 hour for page cache
        'OPTIONS': {
            'MAX_ENTRIES': 500,
        },
    },
    'static_cache': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'static-cache',
        'TIMEOUT': 31536000,  # 1 year for static content
        'OPTIONS': {
            'MAX_ENTRIES': 2000,
        },
    },
}

# Cache key prefixes
CACHE_KEY_PREFIX = 'sabor_con_flow'

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = 'page_cache'
CACHE_MIDDLEWARE_SECONDS = 3600  # 1 hour
CACHE_MIDDLEWARE_KEY_PREFIX = 'page'

# Enable cache versioning for cache busting
CACHE_VERSION = 1

# Session configuration for performance
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Database optimization settings
if not DEBUG:
    # Production database optimizations
    DATABASES['default']['CONN_MAX_AGE'] = 60  # Persistent connections
    DATABASES['default']['OPTIONS'].update({
        'init_command': 'PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=1000; PRAGMA temp_store=MEMORY;',
    })

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@saborconflowdance.com')

# Fallback to console backend for development if email not configured
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    if DEBUG:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        print("Warning: Email credentials not configured. Using console backend for development.")
    else:
        print("Warning: Email credentials not configured in production environment.")

# Google Analytics 4 Configuration - SPEC_05 Group A Task 3
GA4_MEASUREMENT_ID = os.environ.get('GA4_MEASUREMENT_ID')
GA4_DEBUG_MODE = os.environ.get('GA4_DEBUG_MODE', 'False').lower() in ('true', '1', 't')
GA4_ANONYMIZE_IP = os.environ.get('GA4_ANONYMIZE_IP', 'True').lower() in ('true', '1', 't')
GA4_RESPECT_DNT = os.environ.get('GA4_RESPECT_DNT', 'True').lower() in ('true', '1', 't')

# Analytics Features
ENABLE_ANALYTICS = os.environ.get('ENABLE_ANALYTICS', 'True').lower() in ('true', '1', 't')

# Google Maps Configuration - SPEC_05 Group D Task 11
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')
GOOGLE_MAPS_ZOOM_LEVEL = int(os.environ.get('GOOGLE_MAPS_ZOOM_LEVEL', '16'))
STUDIO_COORDINATES = {
    'latitude': float(os.environ.get('STUDIO_LATITUDE', '40.0150')),
    'longitude': float(os.environ.get('STUDIO_LONGITUDE', '-105.2705'))
}
ENABLE_GOOGLE_MAPS = os.environ.get('ENABLE_GOOGLE_MAPS', 'True').lower() in ('true', '1', 't')

# Business Configuration for Analytics
BUSINESS_INFO = {
    'name': os.environ.get('BUSINESS_NAME', 'Sabor Con Flow Dance'),
    'address': os.environ.get('BUSINESS_ADDRESS', 'Avalon Ballroom, Boulder, CO'),
    'phone': os.environ.get('BUSINESS_PHONE', '(555) 123-4567'),
    'email': os.environ.get('BUSINESS_EMAIL', 'info@saborconflowdance.com'),
}

# Class Pricing for Enhanced Ecommerce
CLASS_PRICING = {
    'drop_in': int(os.environ.get('PRICE_DROP_IN', '20')),
    'package_4': int(os.environ.get('PRICE_4_CLASS_PACKAGE', '70')),
    'package_8': int(os.environ.get('PRICE_8_CLASS_PACKAGE', '120')),
    'private_lesson': int(os.environ.get('PRICE_PRIVATE_LESSON', '80')),
    'workshop': int(os.environ.get('PRICE_WORKSHOP', '30')),
}

# Pastio.fun Integration Configuration - SPEC_05 Group B Task 7
PASTIO_API_KEY = os.environ.get('PASTIO_API_KEY')
PASTIO_ORGANIZER_ID = os.environ.get('PASTIO_ORGANIZER_ID', 'sabor-con-flow-dance')
PASTIO_WEBHOOK_SECRET = os.environ.get('PASTIO_WEBHOOK_SECRET')

# Instagram Integration Configuration - SPEC_04 Group D
INSTAGRAM_WEBHOOK_VERIFY_TOKEN = os.environ.get('INSTAGRAM_WEBHOOK_VERIFY_TOKEN')

# Database Performance Monitoring - SPEC_06 Group B Task 6
ENABLE_DB_PERFORMANCE_MONITORING = os.environ.get('ENABLE_DB_PERFORMANCE_MONITORING', 'True').lower() in ('true', '1', 't')
DB_SLOW_QUERY_THRESHOLD = int(os.environ.get('DB_SLOW_QUERY_THRESHOLD', '100'))  # milliseconds
DB_CRITICAL_QUERY_THRESHOLD = int(os.environ.get('DB_CRITICAL_QUERY_THRESHOLD', '500'))  # milliseconds
DB_TOO_MANY_QUERIES_THRESHOLD = int(os.environ.get('DB_TOO_MANY_QUERIES_THRESHOLD', '50'))  # query count

# Redis Cache Configuration (when available)
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL and not DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 20,
                    'retry_on_timeout': True,
                },
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            },
            'KEY_PREFIX': 'sabor_con_flow',
            'TIMEOUT': 1800,  # 30 minutes default
        }
    }

# Sentry Configuration for Error Tracking - SPEC_06 Group C Task 9
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

SENTRY_DSN = os.environ.get('SENTRY_DSN')
SENTRY_ENVIRONMENT = os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development')
SENTRY_RELEASE = os.environ.get('SENTRY_RELEASE', 'sabor-con-flow@1.0.0')

if SENTRY_DSN:
    sentry_logging = LoggingIntegration(
        level=logging.INFO,        # Capture info and above as breadcrumbs
        event_level=logging.ERROR  # Send errors as events
    )
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
                signals_spans=True,
                cache_spans=True,
            ),
            sentry_logging,
        ],
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        
        # Performance Monitoring
        traces_sample_rate=0.1 if not DEBUG else 1.0,  # 10% in production, 100% in development
        profiles_sample_rate=0.1 if not DEBUG else 1.0,
        
        # Error Filtering
        before_send=lambda event, hint: event if not DEBUG or event.get('level') == 'error' else None,
        
        # Additional Options
        attach_stacktrace=True,
        send_default_pii=False,  # Don't send personally identifiable information
        max_breadcrumbs=50,
        debug=DEBUG,
        
        # Custom Tags
        default_integrations=True,
    )
    
    # Set custom tags for better error organization
    sentry_sdk.set_tag("application", "sabor-con-flow-dance")
    sentry_sdk.set_tag("component", "django-backend")

# Monitoring Configuration - SPEC_06 Group C Task 9
ENABLE_MONITORING = os.environ.get('ENABLE_MONITORING', 'True').lower() in ('true', '1', 't')
MONITORING_ALERT_EMAIL = os.environ.get('MONITORING_ALERT_EMAIL', ADMIN_EMAIL)

# UptimeRobot Configuration
UPTIMEROBOT_API_KEY = os.environ.get('UPTIMEROBOT_API_KEY')
UPTIMEROBOT_MONITOR_URL = os.environ.get('UPTIMEROBOT_MONITOR_URL', 'https://your-domain.vercel.app/health/')

# Performance Monitoring Thresholds
PERFORMANCE_THRESHOLDS = {
    'response_time_warning': int(os.environ.get('PERF_RESPONSE_TIME_WARNING', '1000')),  # ms
    'response_time_critical': int(os.environ.get('PERF_RESPONSE_TIME_CRITICAL', '3000')),  # ms
    'error_rate_warning': float(os.environ.get('PERF_ERROR_RATE_WARNING', '5.0')),  # percentage
    'error_rate_critical': float(os.environ.get('PERF_ERROR_RATE_CRITICAL', '10.0')),  # percentage
    'cpu_usage_warning': int(os.environ.get('PERF_CPU_WARNING', '80')),  # percentage
    'memory_usage_warning': int(os.environ.get('PERF_MEMORY_WARNING', '85')),  # percentage
    'disk_usage_warning': int(os.environ.get('PERF_DISK_WARNING', '90')),  # percentage
}

# Alert Configuration
ALERT_CHANNELS = {
    'email': {
        'enabled': bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD),
        'recipients': [MONITORING_ALERT_EMAIL] if MONITORING_ALERT_EMAIL else [],
    },
    'slack': {
        'enabled': bool(os.environ.get('SLACK_WEBHOOK_URL')),
        'webhook_url': os.environ.get('SLACK_WEBHOOK_URL'),
        'channel': os.environ.get('SLACK_ALERT_CHANNEL', '#alerts'),
    },
    'sentry': {
        'enabled': bool(SENTRY_DSN),
        'level': 'error',
    }
}

# Health Check Configuration
HEALTH_CHECK_TIMEOUT = int(os.environ.get('HEALTH_CHECK_TIMEOUT', '30'))  # seconds
HEALTH_CHECK_CACHE_TTL = int(os.environ.get('HEALTH_CHECK_CACHE_TTL', '60'))  # seconds

# Application Version for Monitoring
APP_VERSION = os.environ.get('APP_VERSION', '1.0.0')
